### PR TITLE
Update react dependencies to at least 16, not only 16.

### PR DESCRIPTION
**Pull request by fsargent**

### CODE REVIEW

**Comment by fsargent** [comment]
@estrattonbailey Would love your review on this!

**Comment by estrattonbailey** [comment]
@fsargent nice! Thanks for this 🙌 mind just reformatting the commit message to match the rest of the repo?

Do you need this to release a new patch version? If so, it needs to be something like `patch: update react dep` that follows [conventional commit patterns.](https://www.conventionalcommits.org/en/v1.0.0/) `patch` === patch version, `feat` === minor version. Patch should work for this.

**Comment by fsargent** [comment]
Done @estrattonbailey

**Comment by estrattonbailey** [comment]
Brain fart, was on mobile. `fix` is the correct prefix, my bad, and I had to update the pnpm lockfile lol. `1.3.4` just went out!

**Pull request merged**
